[package]
name = "dupesearch"
version = "0.1.13"
authors = ["wookie184 <wookie1840@gmail.com>"]
edition = "2021"

[lib]
name = "dupesearch"
crate-type = ["cdylib"]

[dependencies]
walkdir="2.3"
crc="2.1"
threadpool="1.8"

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]
