# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            python-versions: "3.7 3.8 3.9"
            architectures: "x64"
          - os: windows-latest
            python-versions: "3.7 3.8 3.9"
            architectures: "x64 x86"
          - os: macos-latest
            python-versions: "3.7 3.8 3.9"
            architectures: "x64"


    steps:
    - uses: actions/checkout@v2

    # setup-python does not support matrix https://github.com/actions/setup-python/issues/98
    # so just run it for each python version needed.
    - name: Set up Python 3.7
      uses: wookie184/setup-python @v2
      with:
        python-version: ${{ matrix.python-versions }}
        architecture: ${{ matrix.architectures }}

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Build package
      run: maturin build --strip --release

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels


  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: wheels
        path: wheels

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheels
        verify_metadata: false
        verbose: true
